//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawnshop.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ID { get; set; }
        public Nullable<int> ID_Product { get; set; }
        public Nullable<int> Sum { get; set; }
        public Nullable<System.DateTime> Date_Pay { get; set; }
        public Nullable<System.DateTime> Actual_Date_Pay { get; set; }
        public Nullable<int> Employee { get; set; }
        public string Pay_Status { get; set; }
    
        public virtual Employee Employee1 { get; set; }
        public virtual Product Product { get; set; }
    }
}
